apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  selector:
    app: app
  ports:
    - name: myapp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: app
      protocol: TCP
      port: 8888
      targetPort: 8888
  
  
